server:
  port: 8080
  servlet:
    context-path: ""
logging:
  file:
    name: logs/bus.log
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.sqlite.JDBC
    #    url: jdbc:sqlite:data/database/util.db
    utildb:
      jdbc-url: jdbc:sqlite:data/database/util.db
    commondb:
      #  不能使用url
      jdbc-url: jdbc:sqlite:data/database/common.db
